"""
Compliance Officer Agent (FLAGSHIP)

The AI Compliance Officer serves as your tireless compliance partner,
providing daily briefings, proactive risk monitoring, regulatory Q&A,
and compliance guidance grounded in EU AML regulations.

This is the cornerstone of the AI AML Officer system.

Features:
- Daily/weekly compliance briefings
- Proactive risk monitoring
- Regulatory Q&A with RAG
- New regulation impact assessment
- Compliance report generation
- Exam preparation support
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone


def utc_now() -> datetime:
    """Return current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


from enum import Enum
from typing import Any, Dict, List, Optional

from .base import BaseAgent, AgentContext, AgentResult, AgentRegistry, AgentType

logger = logging.getLogger(__name__)


class AlertPriority(str, Enum):
    """Alert priority levels."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class BriefingType(str, Enum):
    """Types of compliance briefings."""

    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    AD_HOC = "ad_hoc"


@dataclass
class RiskIndicator:
    """A risk indicator or trend."""

    name: str
    current_value: float
    previous_value: float
    trend: str  # "up", "down", "stable"
    severity: str  # "critical", "warning", "normal"
    description: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "current_value": self.current_value,
            "previous_value": self.previous_value,
            "trend": self.trend,
            "severity": self.severity,
            "description": self.description,
            "change_percent": self._calculate_change(),
        }

    def _calculate_change(self) -> float:
        if self.previous_value == 0:
            return 100.0 if self.current_value > 0 else 0.0
        return ((self.current_value - self.previous_value) / self.previous_value) * 100


@dataclass
class ProactiveAlert:
    """A proactive alert generated by the AI."""

    alert_id: str
    priority: AlertPriority
    title: str
    description: str
    category: str
    recommended_action: str
    regulatory_reference: Optional[str] = None
    deadline: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "priority": self.priority.value,
            "title": self.title,
            "description": self.description,
            "category": self.category,
            "recommended_action": self.recommended_action,
            "regulatory_reference": self.regulatory_reference,
            "deadline": self.deadline,
            "created_at": self.created_at.isoformat(),
        }


@dataclass
class DailyBriefing:
    """A daily compliance briefing."""

    briefing_id: str
    briefing_type: BriefingType
    generated_at: datetime
    period_start: datetime
    period_end: datetime

    # Executive summary
    executive_summary: str

    # Alert statistics
    total_alerts: int
    critical_alerts: int
    high_priority_alerts: int
    auto_resolved: int
    pending_review: int

    # Cases
    new_cases: int
    closed_cases: int
    escalated_cases: int

    # SARs
    sars_drafted: int
    sars_filed: int
    sars_pending: int

    # Risk indicators
    risk_indicators: List[RiskIndicator]

    # Proactive alerts
    proactive_alerts: List[ProactiveAlert]

    # Regulatory updates
    regulatory_updates: List[Dict[str, Any]]

    # Deadlines
    upcoming_deadlines: List[Dict[str, Any]]

    # Recommendations
    recommendations: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "briefing_id": self.briefing_id,
            "briefing_type": self.briefing_type.value,
            "generated_at": self.generated_at.isoformat(),
            "period_start": self.period_start.isoformat(),
            "period_end": self.period_end.isoformat(),
            "executive_summary": self.executive_summary,
            "alerts": {
                "total": self.total_alerts,
                "critical": self.critical_alerts,
                "high_priority": self.high_priority_alerts,
                "auto_resolved": self.auto_resolved,
                "pending_review": self.pending_review,
            },
            "cases": {
                "new": self.new_cases,
                "closed": self.closed_cases,
                "escalated": self.escalated_cases,
            },
            "sars": {
                "drafted": self.sars_drafted,
                "filed": self.sars_filed,
                "pending": self.sars_pending,
            },
            "risk_indicators": [ri.to_dict() for ri in self.risk_indicators],
            "proactive_alerts": [pa.to_dict() for pa in self.proactive_alerts],
            "regulatory_updates": self.regulatory_updates,
            "upcoming_deadlines": self.upcoming_deadlines,
            "recommendations": self.recommendations,
        }


@AgentRegistry.register("compliance_officer")
class ComplianceOfficerAgent(BaseAgent):
    """
    The AI Compliance Officer - your autonomous compliance partner.

    This flagship agent provides:
    1. Daily briefings on overnight activity
    2. Proactive risk monitoring
    3. Regulatory Q&A grounded in EU regulations
    4. New regulation impact assessment
    5. Compliance report generation
    """

    BRIEFING_PROMPT = """You are an expert AI Compliance Officer specializing in EU AML/CFT regulations.

Your task is to generate a comprehensive compliance briefing based on the operational data provided.

## EU Regulatory Framework
- AMLD 5 (Directive 2018/843): Enhanced due diligence, beneficial ownership
- AMLD 6 (Directive 2018/1673): Criminal offenses and penalties
- EBA Guidelines: Risk-based approach, internal controls
- FATF Recommendations: International standards

## Operational Data for Period: {period_start} to {period_end}

### Alert Statistics
{alert_stats}

### Case Statistics
{case_stats}

### SAR Statistics
{sar_stats}

### Recent Transactions Summary
{transaction_summary}

### Recent Regulatory Changes
{regulatory_updates}

### System Health
{system_health}

## Instructions

Generate a compliance briefing with the following sections:

1. **Executive Summary** (3-4 sentences)
   - Overall compliance posture
   - Key concerns requiring attention
   - Positive developments

2. **Risk Assessment**
   - Identify emerging risk patterns
   - Evaluate threshold breaches
   - Assess geographic risk exposure

3. **Proactive Alerts**
   - Pattern anomalies that need attention
   - Regulatory deadline reminders
   - System health warnings

4. **Recommendations**
   - Prioritized action items
   - Process improvement suggestions
   - Resource allocation advice

## Response Format (JSON)
{{
    "executive_summary": "3-4 sentence overview",
    "risk_indicators": [
        {{
            "name": "Indicator name",
            "current_value": 0.0,
            "previous_value": 0.0,
            "trend": "up|down|stable",
            "severity": "critical|warning|normal",
            "description": "Explanation"
        }}
    ],
    "proactive_alerts": [
        {{
            "priority": "critical|high|medium|low|info",
            "title": "Alert title",
            "description": "Detailed description",
            "category": "risk|compliance|operational|regulatory",
            "recommended_action": "What to do",
            "regulatory_reference": "EU regulation reference if applicable",
            "deadline": "YYYY-MM-DD if applicable"
        }}
    ],
    "regulatory_concerns": ["List of regulatory concerns"],
    "recommendations": ["Prioritized recommendations"],
    "overall_risk_level": "critical|high|medium|low",
    "compliance_score": 0-100,
    "areas_of_concern": ["Specific areas needing attention"],
    "positive_developments": ["Things going well"]
}}

Important:
- Use only the provided operational/regulatory/system data.
- Do not invent statistics, deadlines, or incidents.
- Return raw JSON only (no Markdown/code fences or extra prose).
"""

    COMPLIANCE_QA_PROMPT = """You are an expert EU AML/CFT Compliance Advisor.

Your role is to answer compliance questions with accuracy and cite relevant regulations.

## EU Regulatory Framework
- AMLD 5 (Directive 2018/843): Fifth Anti-Money Laundering Directive
- AMLD 6 (Directive 2018/1673): Sixth Anti-Money Laundering Directive
- EBA Guidelines on AML/CFT risk factors
- EBA Guidelines on internal governance
- FATF 40 Recommendations
- National implementations of EU directives

## Context from Regulatory Database
{regulatory_context}

## Conversation History
{conversation_history}

## Current Question
{question}

## Instructions

Provide a comprehensive answer that:
1. Directly addresses the question
2. Cites specific EU regulations and articles
3. Explains practical implications
4. Notes any jurisdictional variations
5. Suggests related topics for further reading
6. Clearly distinguish what is supported by the provided context vs. general interpretation
7. If the provided context is insufficient, state the limitation in "caveats"

## Response Format (JSON)
{{
    "answer": "Comprehensive answer to the question",
    "confidence": "high|medium|low",
    "sources": [
        {{
            "title": "Regulation/Directive title",
            "celex_id": "CELEX ID if available",
            "article": "Specific article/section",
            "relevance": "How it relates to the question"
        }}
    ],
    "followup_questions": ["Suggested follow-up questions"],
    "practical_implications": ["Practical takeaways"],
    "caveats": ["Any limitations or caveats"],
    "jurisdictional_notes": "Notes about member state variations if relevant"
}}

Important:
- Ground the answer in the provided regulatory context and question history.
- If the provided context is insufficient, state that in caveats instead of guessing.
- Return raw JSON only (no Markdown/code fences or extra prose).
"""

    IMPACT_ASSESSMENT_PROMPT = """You are an expert EU Regulatory Impact Analyst.

Analyze the impact of the new regulation on the organization's AML/CFT program.

## New Regulation
{regulation_summary}

## Current Compliance Status
{current_status}

## Organization Profile
{org_profile}

## Instructions

Provide a comprehensive impact assessment:

1. **Summary**: Overall impact level and urgency
2. **Affected Areas**: Which parts of the program are affected
3. **Gap Analysis**: What needs to change
4. **Implementation Timeline**: When changes must be made
5. **Resource Requirements**: Estimated effort and cost
6. **Risk if Non-Compliant**: Consequences of missing deadlines

## Response Format (JSON)
{{
    "impact_level": "high|medium|low",
    "urgency": "immediate|short_term|medium_term|long_term",
    "summary": "Overall impact summary",
    "affected_areas": [
        {{
            "area": "Area name",
            "current_state": "Current compliance state",
            "required_state": "What needs to change",
            "gap": "Specific gap",
            "priority": "high|medium|low"
        }}
    ],
    "action_items": [
        {{
            "action": "What to do",
            "responsible": "Who should do it",
            "deadline": "When",
            "effort": "Estimated effort"
        }}
    ],
    "implementation_timeline": "Overall timeline",
    "resource_requirements": {{
        "estimated_hours": 0,
        "skills_needed": ["Skills"],
        "budget_estimate": "Budget range"
    }},
    "non_compliance_risks": ["Risks if not compliant"],
    "recommendations": ["Strategic recommendations"]
}}

Important:
- Use only the provided regulation/current-status/org-profile context.
- Do not invent deadlines, costs, or requirements without support in the input.
- Use null or conservative estimates when information is missing.
- Return raw JSON only (no Markdown/code fences or extra prose).
"""

    @property
    def agent_type(self) -> AgentType:
        return AgentType.COMPLIANCE_OFFICER

    @property
    def system_prompt(self) -> str:
        return self.BRIEFING_PROMPT

    def __init__(self):
        super().__init__()
        self.agent_id = "compliance_officer"
        self.name = "AI Compliance Officer"
        self.description = "Your autonomous compliance partner for EU AML/CFT"

    async def process(self, context: AgentContext) -> AgentResult:
        """
        Process a compliance officer request.

        Supported actions:
        - generate_briefing: Generate daily/weekly briefing
        - answer_question: Answer compliance Q&A
        - assess_impact: Assess regulatory impact
        - monitor_risks: Proactive risk monitoring
        """
        action = context.input_data.get("action", "generate_briefing")

        if action == "generate_briefing":
            return await self._generate_briefing(context)
        elif action == "answer_question":
            return await self._answer_question(context)
        elif action == "assess_impact":
            return await self._assess_impact(context)
        elif action == "monitor_risks":
            return await self._monitor_risks(context)
        else:
            return AgentResult(
                agent_type=self.agent_type,
                success=False,
                result=None,
                confidence=0.0,
                reasoning=f"Unknown action: {action}",
                error=f"Unsupported action: {action}",
            )

    async def _generate_briefing(self, context: AgentContext) -> AgentResult:
        """Generate a compliance briefing."""
        logger.info("Generating compliance briefing")

        try:
            # Extract parameters
            lookback_hours = context.input_data.get("lookback_hours", 24)
            briefing_type = context.input_data.get("briefing_type", BriefingType.DAILY)

            # Get operational data (in production, fetch from database)
            alert_stats = context.input_data.get("alert_stats", self._get_demo_alert_stats())
            case_stats = context.input_data.get("case_stats", self._get_demo_case_stats())
            sar_stats = context.input_data.get("sar_stats", self._get_demo_sar_stats())
            transaction_summary = context.input_data.get(
                "transaction_summary", self._get_demo_transaction_summary()
            )
            regulatory_updates = context.input_data.get(
                "regulatory_updates", self._get_demo_regulatory_updates()
            )
            system_health = context.input_data.get("system_health", self._get_demo_system_health())

            # Calculate period
            period_end = utc_now()
            period_start = period_end - timedelta(hours=lookback_hours)

            # Build prompt
            prompt = self.BRIEFING_PROMPT.format(
                period_start=period_start.strftime("%Y-%m-%d %H:%M"),
                period_end=period_end.strftime("%Y-%m-%d %H:%M"),
                alert_stats=self._format_stats(alert_stats),
                case_stats=self._format_stats(case_stats),
                sar_stats=self._format_stats(sar_stats),
                transaction_summary=transaction_summary,
                regulatory_updates=regulatory_updates,
                system_health=self._format_stats(system_health),
            )
            context.input_data["_prompt_version"] = "compliance_officer.briefing.2026-02-25.1"

            # Call Claude
            response = await self.call_claude(prompt, context)

            # Build briefing object
            briefing = self._build_briefing(
                response=response,
                alert_stats=alert_stats,
                case_stats=case_stats,
                sar_stats=sar_stats,
                period_start=period_start,
                period_end=period_end,
                briefing_type=briefing_type,
            )

            return AgentResult(
                agent_type=self.agent_type,
                success=True,
                result=briefing.to_dict(),
                confidence=self.calculate_confidence(response),
                reasoning="Generated comprehensive compliance briefing",
                metadata={
                    "briefing_type": (
                        briefing_type.value
                        if isinstance(briefing_type, BriefingType)
                        else briefing_type
                    ),
                    "period_hours": lookback_hours,
                    "risk_level": response.get("overall_risk_level", "medium"),
                    "compliance_score": response.get("compliance_score", 75),
                },
            )

        except Exception as e:
            logger.error(f"Briefing generation error: {e}")
            return AgentResult(
                agent_type=self.agent_type,
                success=False,
                result=None,
                confidence=0.0,
                reasoning=f"Failed to generate briefing: {str(e)}",
                error=str(e),
            )

    async def _answer_question(self, context: AgentContext) -> AgentResult:
        """Answer a compliance question using RAG."""
        logger.info("Processing compliance question")

        try:
            question = context.input_data.get("question", "")
            conversation_history = context.input_data.get("conversation_history", [])
            regulatory_context = context.input_data.get("regulatory_context", "")

            if not question:
                return AgentResult(
                    agent_type=self.agent_type,
                    success=False,
                    result=None,
                    confidence=0.0,
                    reasoning="No question provided",
                    error="Question is required",
                )

            # If no regulatory context provided, use default EU AML context
            if not regulatory_context:
                regulatory_context = self._get_default_regulatory_context()

            # Format conversation history
            history_text = ""
            if conversation_history:
                for msg in conversation_history[-5:]:  # Last 5 messages
                    role = msg.get("role", "user")
                    content = msg.get("content", "")
                    history_text += f"\n{role.upper()}: {content}"

            # Build prompt
            prompt = self.COMPLIANCE_QA_PROMPT.format(
                regulatory_context=regulatory_context,
                conversation_history=history_text or "No previous conversation",
                question=question,
            )
            context.input_data["_prompt_version"] = "compliance_officer.qa.2026-02-25.1"

            # Call Claude
            response = await self.call_claude(prompt, context)

            return AgentResult(
                agent_type=self.agent_type,
                success=True,
                result={
                    "question": question,
                    "answer": response.get("answer", ""),
                    "confidence": response.get("confidence", "medium"),
                    "sources": response.get("sources", []),
                    "followup_questions": response.get("followup_questions", []),
                    "practical_implications": response.get("practical_implications", []),
                    "caveats": response.get("caveats", []),
                    "jurisdictional_notes": response.get("jurisdictional_notes", ""),
                },
                confidence=self.calculate_confidence(response),
                reasoning="Answered compliance question with regulatory citations",
            )

        except Exception as e:
            logger.error(f"Q&A error: {e}")
            return AgentResult(
                agent_type=self.agent_type,
                success=False,
                result=None,
                confidence=0.0,
                reasoning=f"Failed to answer question: {str(e)}",
                error=str(e),
            )

    async def _assess_impact(self, context: AgentContext) -> AgentResult:
        """Assess the impact of a new regulation."""
        logger.info("Assessing regulatory impact")

        try:
            regulation_summary = context.input_data.get("regulation_summary", "")
            current_status = context.input_data.get("current_status", "")
            org_profile = context.input_data.get("org_profile", "")

            prompt = self.IMPACT_ASSESSMENT_PROMPT.format(
                regulation_summary=regulation_summary or "No regulation summary provided",
                current_status=current_status or "Standard EU AML program",
                org_profile=org_profile or "EU-based financial institution",
            )
            context.input_data["_prompt_version"] = "compliance_officer.impact.2026-02-25.1"

            response = await self.call_claude(prompt, context)

            return AgentResult(
                agent_type=self.agent_type,
                success=True,
                result=response,
                confidence=self.calculate_confidence(response),
                reasoning="Completed regulatory impact assessment",
                metadata={
                    "impact_level": response.get("impact_level", "medium"),
                    "urgency": response.get("urgency", "medium_term"),
                },
            )

        except Exception as e:
            logger.error(f"Impact assessment error: {e}")
            return AgentResult(
                agent_type=self.agent_type,
                success=False,
                result=None,
                confidence=0.0,
                reasoning=f"Failed to assess impact: {str(e)}",
                error=str(e),
            )

    async def _monitor_risks(self, context: AgentContext) -> AgentResult:
        """Proactive risk monitoring."""
        logger.info("Monitoring risks proactively")

        # In production, this would analyze real-time data streams
        # For now, return demo proactive alerts
        proactive_alerts = [
            ProactiveAlert(
                alert_id=f"PA-{utc_now().strftime('%Y%m%d%H%M%S')}-001",
                priority=AlertPriority.HIGH,
                title="Unusual Transaction Pattern Detected",
                description="Transaction velocity for customer segment 'High Net Worth' has increased 45% above baseline in the last 4 hours.",
                category="risk",
                recommended_action="Review recent transactions in HNW segment and verify legitimacy",
                regulatory_reference="AMLD 5, Article 18 - Enhanced due diligence",
            ),
            ProactiveAlert(
                alert_id=f"PA-{utc_now().strftime('%Y%m%d%H%M%S')}-002",
                priority=AlertPriority.MEDIUM,
                title="SAR Filing Deadline Approaching",
                description="3 SAR drafts have been pending review for more than 48 hours.",
                category="compliance",
                recommended_action="Expedite SAR review process to meet reporting timelines",
                deadline=(utc_now() + timedelta(days=2)).strftime("%Y-%m-%d"),
            ),
            ProactiveAlert(
                alert_id=f"PA-{utc_now().strftime('%Y%m%d%H%M%S')}-003",
                priority=AlertPriority.INFO,
                title="New EBA Guidelines Published",
                description="EBA has published updated guidelines on remote customer onboarding.",
                category="regulatory",
                recommended_action="Review new guidelines and assess impact on current procedures",
                regulatory_reference="EBA/GL/2022/15",
            ),
        ]

        return AgentResult(
            agent_type=self.agent_type,
            success=True,
            result={
                "proactive_alerts": [pa.to_dict() for pa in proactive_alerts],
                "monitoring_timestamp": utc_now().isoformat(),
                "next_check": (utc_now() + timedelta(hours=1)).isoformat(),
            },
            confidence=0.85,
            reasoning="Completed proactive risk monitoring scan",
        )

    def _build_briefing(
        self,
        response: Dict[str, Any],
        alert_stats: Dict[str, Any],
        case_stats: Dict[str, Any],
        sar_stats: Dict[str, Any],
        period_start: datetime,
        period_end: datetime,
        briefing_type: BriefingType,
    ) -> DailyBriefing:
        """Build a DailyBriefing from Claude's response."""

        # Parse risk indicators
        risk_indicators = [
            RiskIndicator(
                name=ri.get("name", ""),
                current_value=float(ri.get("current_value", 0)),
                previous_value=float(ri.get("previous_value", 0)),
                trend=ri.get("trend", "stable"),
                severity=ri.get("severity", "normal"),
                description=ri.get("description", ""),
            )
            for ri in response.get("risk_indicators", [])
        ]

        # Parse proactive alerts
        proactive_alerts = [
            ProactiveAlert(
                alert_id=f"PA-{utc_now().strftime('%Y%m%d%H%M%S')}-{i:03d}",
                priority=AlertPriority(pa.get("priority", "medium")),
                title=pa.get("title", ""),
                description=pa.get("description", ""),
                category=pa.get("category", "risk"),
                recommended_action=pa.get("recommended_action", ""),
                regulatory_reference=pa.get("regulatory_reference"),
                deadline=pa.get("deadline"),
            )
            for i, pa in enumerate(response.get("proactive_alerts", []))
        ]

        return DailyBriefing(
            briefing_id=f"BRIEF-{utc_now().strftime('%Y%m%d%H%M%S')}",
            briefing_type=(
                briefing_type
                if isinstance(briefing_type, BriefingType)
                else BriefingType(briefing_type)
            ),
            generated_at=utc_now(),
            period_start=period_start,
            period_end=period_end,
            executive_summary=response.get("executive_summary", ""),
            total_alerts=alert_stats.get("total", 0),
            critical_alerts=alert_stats.get("critical", 0),
            high_priority_alerts=alert_stats.get("high", 0),
            auto_resolved=alert_stats.get("auto_resolved", 0),
            pending_review=alert_stats.get("pending_review", 0),
            new_cases=case_stats.get("new", 0),
            closed_cases=case_stats.get("closed", 0),
            escalated_cases=case_stats.get("escalated", 0),
            sars_drafted=sar_stats.get("drafted", 0),
            sars_filed=sar_stats.get("filed", 0),
            sars_pending=sar_stats.get("pending", 0),
            risk_indicators=risk_indicators,
            proactive_alerts=proactive_alerts,
            regulatory_updates=response.get("regulatory_concerns", []),
            upcoming_deadlines=[],  # Would be populated from database
            recommendations=response.get("recommendations", []),
        )

    def _format_stats(self, stats: Dict[str, Any]) -> str:
        """Format statistics for the prompt."""
        lines = []
        for key, value in stats.items():
            formatted_key = key.replace("_", " ").title()
            lines.append(f"- {formatted_key}: {value}")
        return "\n".join(lines)

    def _get_demo_alert_stats(self) -> Dict[str, Any]:
        """Get demo alert statistics."""
        return {
            "total": 47,
            "critical": 2,
            "high": 8,
            "medium": 22,
            "low": 15,
            "auto_resolved": 18,
            "pending_review": 12,
            "escalated_to_case": 5,
            "false_positive_rate": 38.3,
        }

    def _get_demo_case_stats(self) -> Dict[str, Any]:
        """Get demo case statistics."""
        return {
            "total_open": 23,
            "new": 5,
            "closed": 3,
            "escalated": 2,
            "avg_resolution_time_hours": 72,
            "oldest_open_days": 14,
        }

    def _get_demo_sar_stats(self) -> Dict[str, Any]:
        """Get demo SAR statistics."""
        return {
            "drafted": 3,
            "pending_review": 2,
            "filed": 1,
            "pending": 4,
            "avg_prep_time_hours": 4.5,
        }

    def _get_demo_transaction_summary(self) -> str:
        """Get demo transaction summary."""
        return """
Transaction Volume: 12,847 transactions processed
Total Value: €45.2M
High-Risk Transactions: 234 (1.8%)
Cross-Border: 3,421 (26.6%)
Geographic Distribution:
  - Domestic: 73.4%
  - EU: 18.2%
  - Non-EU High-Risk: 2.1%
  - Other: 6.3%
Unusual Patterns Detected: 12
"""

    def _get_demo_regulatory_updates(self) -> str:
        """Get demo regulatory updates."""
        return """
Recent Regulatory Developments:
1. EBA published final guidelines on remote customer onboarding (EBA/GL/2022/15)
2. EU Commission proposed amendments to AMLD framework
3. FATF updated mutual evaluation procedures
4. ECB issued statement on crypto-asset risks
"""

    def _get_demo_system_health(self) -> Dict[str, Any]:
        """Get demo system health."""
        return {
            "api_uptime_percent": 99.9,
            "avg_response_time_ms": 145,
            "queue_depth": 23,
            "sanctions_list_age_hours": 2,
            "last_full_scan_hours_ago": 6,
        }

    def _get_default_regulatory_context(self) -> str:
        """Get default EU AML regulatory context."""
        return """
## Key EU AML/CFT Regulations

### AMLD 5 (Directive 2018/843)
- Enhanced CDD for high-risk third countries
- Beneficial ownership register access
- Virtual currency provider regulation
- Reduced anonymous instrument limits

### AMLD 6 (Directive 2018/1673)
- Harmonized predicate offenses (22 categories)
- Criminal liability for legal persons
- Enhanced penalties (minimum 4 years imprisonment)
- Extended extraterritorial jurisdiction

### EBA Guidelines
- Risk-based approach to AML/CFT
- Internal governance requirements
- Customer due diligence procedures
- Suspicious transaction reporting

### Key Thresholds (EU)
- CDD threshold: €15,000 (occasional transactions)
- Enhanced CDD: PEPs, high-risk countries, complex structures
- Beneficial ownership: >25% ownership/control
- Cash payment limit: Varies by member state (€3,000-€15,000)

### Reporting Obligations
- STR/SAR: Without delay upon suspicion
- CTR: Varies by jurisdiction
- Cross-border cash: >€10,000
"""
