"""Initial schema

Revision ID: 32fb4bec9bf8
Revises: 
Create Date: 2026-01-06 11:14:25.418496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32fb4bec9bf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    dialect = bind.dialect.name
    json_type = postgresql.JSONB(astext_type=sa.Text()) if dialect == "postgresql" else sa.JSON()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celex', sa.String(), nullable=False),
    sa.Column('eli', sa.String(), nullable=True),
    sa.Column('cellar_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('entry_into_force_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_celex'), 'legal_documents', ['celex'], unique=True)
    op.create_index(op.f('ix_legal_documents_cellar_id'), 'legal_documents', ['cellar_id'], unique=True)
    op.create_index(op.f('ix_legal_documents_eli'), 'legal_documents', ['eli'], unique=False)
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('rss_url', sa.String(), nullable=True),
    sa.Column('query_json', json_type, nullable=False),
    sa.Column('curated_celex_json', json_type, nullable=True),
    sa.Column('recipients_json', json_type, nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('watchlist_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['legal_documents.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_table('legal_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_doc_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('to_doc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_doc_id'], ['legal_documents.id'], ),
    sa.ForeignKeyConstraint(['to_doc_id'], ['legal_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_relations_id'), 'legal_relations', ['id'], unique=False)
    op.create_table('legal_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['legal_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_versions_id'), 'legal_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_versions_id'), table_name='legal_versions')
    op.drop_table('legal_versions')
    op.drop_index(op.f('ix_legal_relations_id'), table_name='legal_relations')
    op.drop_table('legal_relations')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_eli'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_cellar_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_celex'), table_name='legal_documents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
