"""add_compliance_fields

Revision ID: eecefacf821c
Revises: 32fb4bec9bf8
Create Date: 2026-01-07 08:51:48.678808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eecefacf821c'
down_revision: Union[str, Sequence[str], None] = '32fb4bec9bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    dialect = bind.dialect.name
    json_type = postgresql.JSONB(astext_type=sa.Text()) if dialect == "postgresql" else sa.JSON()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_documents', sa.Column('compliance_domain', sa.String(), nullable=True))
    op.add_column('legal_documents', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('legal_documents', sa.Column('implementation_deadline', sa.DateTime(), nullable=True))
    op.add_column('legal_documents', sa.Column('jurisdictional_scope', sa.String(), nullable=True))
    op.add_column('legal_documents', sa.Column('obligations_json', json_type, nullable=True))
    op.add_column('legal_documents', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('legal_documents', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_documents', 'analyzed_at')
    op.drop_column('legal_documents', 'ai_summary')
    op.drop_column('legal_documents', 'obligations_json')
    op.drop_column('legal_documents', 'jurisdictional_scope')
    op.drop_column('legal_documents', 'implementation_deadline')
    op.drop_column('legal_documents', 'risk_level')
    op.drop_column('legal_documents', 'compliance_domain')
    # ### end Alembic commands ###
