[mypy]
python_version = 3.12
ignore_missing_imports = True
explicit_package_bases = True
no_implicit_optional = False
strict_optional = False
check_untyped_defs = False
disable_error_code = dict-item, misc, var-annotated, arg-type, call-arg, assignment, attr-defined, annotation-unchecked, import-untyped, return-value, operator, valid-type, index, return
